ktor:
    deployment:
        port: 8060
    application:
        modules:
            - com.Biodex.ApplicationKt.module


db:
    url: "jdbc:postgresql://localhost:8080/Biodex"
    driver: "org.postgresql.Driver"
    user: "postgres"
    password: "cesaryair"
    poolSize: 10